[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.8
blur = true
startup_mode = "Maximized"
dynamic_title = true

[scrolling]
history = 50000
multiplier = 3

[font]
normal.family = "MesloLGS Nerd Font Mono"
normal.style = "Regular"
bold.family = "MesloLGS Nerd Font Mono"
bold.style = "Bold"
italic.family = "MesloLGS Nerd Font Mono"
italic.style = "Italic"
size = 14

[bell]
duration = 0

[cursor]
style.shape = "Block"
style.blinking = "Off"
vi_mode_style.shape = "Block"
vi_mode_style.blinking = "Off"

[selection]
save_to_clipboard = true

[general]
import = ["~/.config/alacritty/themes/coolnight.toml"]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001b\r"
