"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#2cf9ed)\
[  ](bg:#2cf9ed fg:#001f30)\
[](bg:#0ea5c0 fg:#2cf9ed)\
$directory\
[](fg:#0ea5c0 bg:#0a4a65)\
$git_branch\
$git_status\
[](fg:#0a4a65 bg:#02202f)\
$nodejs\
$bun\
$rust\
$golang\
$php\
[](fg:#02202f bg:#010d18)\
$time\
[ ](fg:#010d18)\
\n$character"""

[directory]
style = "fg:#001f30 bg:#0ea5c0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#0a4a65"
format = '[[ $symbol $branch ](fg:#2cf9ed bg:#0a4a65)]($style)'

[git_status]
style = "bg:#0a4a65"
format = '[[($all_status$ahead_behind )](fg:#2cf9ed bg:#0a4a65)]($style)'

[nodejs]
symbol = ""
style = "bg:#02202f"
format = '[[ $symbol ($version) ](fg:#2cf9ed bg:#02202f)]($style)'

[bun]
symbol = ""
style = "bg:#02202f"
format = '[[ $symbol ($version) ](fg:#2cf9ed bg:#02202f)]($style)'

[rust]
symbol = ""
style = "bg:#02202f"
format = '[[ $symbol ($version) ](fg:#2cf9ed bg:#02202f)]($style)'

[golang]
symbol = ""
style = "bg:#02202f"
format = '[[ $symbol ($version) ](fg:#2cf9ed bg:#02202f)]($style)'

[php]
symbol = ""
style = "bg:#02202f"
format = '[[ $symbol ($version) ](fg:#2cf9ed bg:#02202f)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#010d18"
format = '[[  $time ](fg:#6c7086 bg:#010d18)]($style)'
