set -g status-position bottom
set -g status-justify centre
set -g status on
set -g status-left-length 110
set -g status-right-length 130
set -g status-style "bg=colour235,fg=colour252"

set -g message-style "bg=colour238,fg=colour255"
set -g mode-style "bg=colour24,fg=colour255"

set -g pane-border-style "fg=colour238"
set -g pane-active-border-style "fg=colour81"

set -g window-status-separator ""
set -g window-status-style "bg=colour235,fg=colour244"
set -g window-status-current-style "bg=colour237,fg=colour81,bold"
set -g window-status-format " #[fg=colour244]#I:#W #[default]"
set -g window-status-current-format " #[fg=colour235,bg=colour81,bold] #I:#W #[default]"
set -g window-status-activity-style "fg=colour179,bold"
set -g window-status-bell-style "fg=colour210,bold"

set -g status-left "#{?client_prefix,#[fg=colour235,bg=colour179,bold] CMD #[default],}#[fg=colour81,bold] #S #[fg=colour244]|#[fg=colour250] #{=/40/...:#{b:pane_current_path}} "

set -g status-right "#{?#{&&:#{!=:#{@online_status},},#{!=:#{online_status},}},#[fg=colour114] net:#{online_status} #[fg=colour244]| ,}#{?#{&&:#{!=:#{@batt_remain_short},},#{!=:#{battery_percentage},}},#[fg=colour221] bat:#{battery_percentage} #[fg=colour244]| ,}#[fg=colour250]%a %b %d #[fg=colour81]%H:%M "
