source-file ~/.config/tmux/conf/core.conf
source-file ~/.config/tmux/conf/keybinds.conf
source-file ~/.config/tmux/conf/workflows.conf
source-file ~/.config/tmux/conf/theme.conf
source-file ~/.config/tmux/conf/plugins.conf
