
[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 14

[general]
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

#for video
# size = 35.0
